# Generated by Django 4.0.4 on 2022-05-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_up_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.CharField(default='Please enter something', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='steamID',
            field=models.IntegerField(default=0),
        ),
    ]
