# Generated by Django 4.0.4 on 2022-05-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_up_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=0),
        ),
    ]
