# Generated by Django 4.0.4 on 2022-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_up_api', '0003_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.TextField(default='mm/dd/yy'),
        ),
    ]
