# Generated by Django 4.0.4 on 2022-05-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_up_api', '0004_alter_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
